### ISSUE TITLE
Add support for Macaca fascicularis

### ISSUE THREAD

**Issue by lianos** [igordot/babelgene#1]
Thank you for this very useful package!

Would  it be possible to add support for the [Macaca fascicularis](https://en.wikipedia.org/wiki/Crab-eating_macaque) monkey, please?

I am happy to attempt a patch for consideration, if interested.

Thanks!

**Comment by igordot** [comment]
Thank you for the suggestion.

For now, I am just using the species available in HCOP, so I rely on their decision about which species to include. As you have probably already seen, Macaca mulatta (NCBI taxon ID 9544) is included. Is Macaca fascicularis (9541) substantially different? Given how imperfect the orthology prediction tools are, I wonder if they would even be able to capture the differences within a genus.

**Comment by lianos** [comment]
Ahhh ... Sorry, I had known you used HCOP internally but didn't realize cyno wasn't there.

I was just looking to see if this could be used as an alternative "internet connection free" method to `biomaRt::getLDS()` to get homologous ensembl identifiers for cyno. I cannot say the degree to which the two monkeys are different at the genome level, but they are quite different at the identifier level :-)

Anyway, thanks for the quick response and sorry not to have dug a bit deeper into the species supported by HCOP before posting.

**Comment by igordot** [comment]
No problem.

Yes, having a stable offline option was one of the main reasons behind creating this package. I used to retrieve directly from HCOP, but as with any internet resource, it's possible to run into connection issues.
