### ISSUE TITLE
If `NA` is in gene vector, `orthologs()` returns only one gene row.

### ISSUE THREAD

**Issue by tnieuwe** [igordot/babelgene#3]
Hello!

 I want to start off by saying thank you for making this package, it has been quite useful. I have found what I might think is a bug. Basically if a gene vector fed into orthologs includes an NA, the returned table for that vector will only include one row. I have created an example of this below

```
library(babelgene)
### Using `ortholog()` to find human orthologs of mouse genes ###
gene_vect <- c("Ifit1bl1", "Ifit3b", "Ifit3", "Ifit1", "Cxcl10")
orthologs(genes = gene_vect, species = "mouse", human = FALSE)
### If you add an NA to a gene vector that was previously working, ###
### it will now only return one row (for GCAT in this example) ###
gene_vectNA <- append(gene_vect, NA)
orthologs(genes = gene_vectNA, species = "mouse", human = FALSE)
```

I'm not sure if this is intentional or not, but I just wanted to bring it to your attention if you didn't know about it.

Thanks!
Tim N

**Comment by igordot** [comment]
Thank you for bringing this to my attention. I have not considered the possibility of an NA mixed with valid symbols, but this seems like a relatively common situation.

**Comment by igordot** [comment]
This is now fixed on GitHub and will be included in the next CRAN release. NA genes will be ignored, which is probably the expected behavior.
