### ISSUE TITLE
Finding Post Speciation Paralogs

### ISSUE THREAD

**Issue by olaf-c** [igordot/babelgene#5]
Hi, 

Zebrafish have had a whole genome duplication relative to humans and I would like to be able to grab both homologs. 
Is there a way to adjust the parameters of your package to get these? For example:
COL10A1 collagen type X alpha 1 chain [ Homo sapiens (human) ]
Gene ID: 1300

and retrieving BOTH:
col10a1a collagen, type X, alpha 1a [ Danio rerio (zebrafish) ]
Gene ID: 558919,

AND it's paralog
col10a1b collagen, type X, alpha 1b [ Danio rerio (zebrafish) ]
Gene ID: 555804

**Comment by igordot** [comment]
By default, only col10a1a is returned because it appears in more databases. You can get both genes if you use `top = FALSE`.

```
> babelgene::orthologs(genes = "COL10A1", species = "zebrafish")
  human_symbol human_entrez   human_ensembl taxon_id   symbol entrez            ensembl                                            support support_n
1      COL10A1         1300 ENSG00000123500     7955 col10a1a 558919 ENSDARG00000054753 EggNOG|Ensembl|HomoloGene|OMA|OrthoDB|Treefam|ZFIN         7

> babelgene::orthologs(genes = "COL10A1", species = "zebrafish", top = FALSE)
  human_symbol human_entrez   human_ensembl taxon_id   symbol entrez            ensembl                                            support support_n
1      COL10A1         1300 ENSG00000123500     7955 col10a1a 558919 ENSDARG00000054753 EggNOG|Ensembl|HomoloGene|OMA|OrthoDB|Treefam|ZFIN         7
2      COL10A1         1300 ENSG00000123500     7955 col10a1b 555804 ENSDARG00000101535           Ensembl|HomoloGene|NCBI|OMA|OrthoDB|ZFIN         6
```
